name = "my-app"
compatibility_date = "2024-08-30"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmFlNmNmMDQtZmZlMS00MjE2LWI5OGItNTY5MDAzNmU0NTZlIiwidGVuYW50X2lkIjoiNDM4ZDRjODgyNTNmYjFlYmJiOGI4NzE0MmVhOThkNmU0OTdiZjU5YWE5NWE2ZGQ3MjU1MDg2ZjhmY2RiN2ZiYyIsImludGVybmFsX3NlY3JldCI6IjY0Njg3ZDMwLWE1MmEtNGE2MS05ZGJkLWVlMjA2ZTQxMjMzNSJ9.xG_NpqFxI3Ph3s1d1yychUOmE3aRtmgfrPiCvJJiWnQ"
JWT_SECRET = "JSON-SECRET"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"